[tool.poetry]
name = "gorzdrav-bot"
version = "0.1.0"
description = ""
authors = ["KllRaz <kllraz@yandex.ru>"]
readme = "README.md"
packages = [{include = "gorzdrav_bot"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
